#!/usr/bin/env python3
"""Build vibe-calc.html — the single-file offline version of the site.

Assembles index.html with styles.css inlined into a <style> tag and app.js
inlined into a <script> tag, producing one self-contained file that runs
offline with no internet and no other files.

Run from the project root:

    python3 build-offline.py

The output is generated — edit index.html / styles.css / app.js and re-run
this script to keep vibe-calc.html in sync.
"""

import pathlib

ROOT = pathlib.Path(__file__).parent
SRC_CSS = ROOT / "styles.css"
SRC_JS = ROOT / "app.js"
SRC_HTML = ROOT / "index.html"
OUT = ROOT / "vibe-calc.html"

HEADER = """<!doctype html>
<!-- ============================================================
     VIBE CALC — single-file offline build
     Everything (CSS + JS) is inlined, so this one file runs
     anywhere with no internet and no other files.
     To use: double-click this file, or open it in any browser.
     NOTE: generated by build-offline.py — edit index.html /
     styles.css / app.js instead, then rebuild.
     ============================================================ -->
"""

# The download button belongs to the hosted site, not to the artifact
# itself (the artifact IS the download target).
DOWNLOAD_BLOCK = """    <div class="download">
      <a class="download-btn" href="vibe-calc.html" download="vibe-calc-offline.html">⬇ download &amp; run offline</a>
      <p class="download-note">one little file · no internet needed · works from a USB stick</p>
    </div>

"""


def main() -> None:
    css = SRC_CSS.read_text(encoding="utf-8")
    js = SRC_JS.read_text(encoding="utf-8")
    html = SRC_HTML.read_text(encoding="utf-8")

    if "</style>" in css:
        raise SystemExit("styles.css contains an unexpected '</style>'")
    if "</script>" in js:
        raise SystemExit("app.js contains an unexpected '</script>'")

    link = '<link rel="stylesheet" href="styles.css">'
    script = '<script src="app.js"></script>'
    if link not in html or script not in html:
        raise SystemExit(
            "index.html structure changed — expected the stylesheet link "
            "and the app.js script tag"
        )

    head, body = html.split(link, 1)
    body = body.replace(script, "<script>\n" + js + "\n</script>", 1)

    # drop the hosted-site-only download button from the offline artifact
    if DOWNLOAD_BLOCK not in body:
        raise SystemExit("could not find the .download block in index.html to strip")
    body = body.replace(DOWNLOAD_BLOCK, "", 1)

    out = head + "<style>\n" + css + "\n</style>" + body
    out = out.replace("<!doctype html>\n", "", 1)

    # the CSS classes may legitimately remain (styles.css is inlined as-is),
    # but the download link markup must not be part of the artifact
    if 'class="download"' in out or '<a class="download-btn"' in out:
        raise SystemExit("BUG: download button still present in the artifact")

    OUT.write_text(HEADER + out, encoding="utf-8")
    print(f"built {OUT.name} ({len(out):,} bytes)")


if __name__ == "__main__":
    main()
